def line():
    import math
    variable_a=float(input("Ingrese el coeficiente A:"))
    variable_b=float(input("Ingrese el coeficiente B:"))
    variable_x1=float(input("Ingrese el coeficiente X1:"))
    variable_x2=float(input("Ingrese el coeficiente X2:"))
    print(f"El coeficiente A de su ecuacion de la recta es:{variable_a}")
    print(f"El coeficiente B de su ecuacion de la recta es:{variable_b}")
    print(f"El coeficiente X1 de su ecuacion de la recta es:{variable_x1}")
    print(f"El coeficiente X2 de su ecuacion de la recta es:{variable_x2}")
    print()
    print("Para la siguiente ecuación:")
    print(f"\tY = {variable_a}x + {variable_b}")
    variable_y1=((variable_a*variable_x1)+variable_b) 
    variable_y2=((variable_a*variable_x2)+variable_b)
    print()
    print("Dados los siguientes puntos:")
    print(f"\tP1 ({variable_x1}, {variable_y1})")
    print(f"\tP2 ({variable_x2}, {variable_y2})")
    print()
    variable_distance= math.dist(variable_y1,variable_y2)
    print(f"La distancia entre ellos es:{variable_distance}")
    
